language: bash

services: docker

env:
  global:
    - secure: "dQLGqG3/CC8Z9tqd7EvGYOWsVyi0Z1+jmv9oZggyikjDsOexS7rDV6ewzDUjgPIKRDTjVsLWdMeoVIe7SAXpSgPdSIYPBeCJrnyppOk1Nq/KmmKh7JQCgxTt5fgusSYu3bY6RyQx+VaQ2S2yxdHxeLtxC4WBUHw1tEV9dv9PvoVCjCLfcCt1rClwY9pVo5s4aCoqD+v72U5/CuGBr1cqQdCr05Ag2tEFnHARZTK+CuFsT0agW8LFm1zlZ3wNwwlIWBDuJCKdyph1KKOdXNgjdeFlZ7jrs+VrxjKfRLv3eSawzibVoC6ptzTogsdGxJqMFtZQ7P98op0NaSD5yEFIR6yJsk4zQJbEJadqYJEjnMf66hyf+oPFJFdTKxC/WIdrt6qdKdrmF+LarTeCNok6L3GBK55HI8pfWeZjhoNJ3JO4KdZdjWCf83/sPFyVFnfqmzYLLCrh7UoKEXlP6xpG0uDJTFHuDdMkQKPVtyoilFoVHbFaRn3tuCcXvlFcxd6lBKj0tdvuW0q41UNY0SDXiC1J4glC0HOq5tiFkADEcKZ8+/Amp/yGwT4KYGB6ZObDT1ZKkJlkEaetAn9zQodTmqaWufLOWvw5xWJDsVGZwLcMw0nBWDogYXdANHzNDcnfb5Uf4vS9ppcX4wrlvvuUmNV6KeCDlTtfR6FNK4HyfuM="
    - secure: "TN7aEOYtDSdJOXNG5O+gdL11S/xqWp8k20GWY8d77pZxjbkY+LyZH+c7nK/PU6LcHd9fthiGsaPyLz+1f5Y3tQTw+rAtX6PMgF5WTWVW0V6tafvfy208wr63+C4yCYXvrzZdxiFkZbkrLRNi5SF7HtB6P5mDze+MJkSCEHgHuoZ/vbNhidhuX7vo2Mft1d74n0lSqZmznlB6RFmNle0Av7HbkaryZDkYd/jxrT/VKZ0rM9SjWtigmDOVdQ7aP5YRGBNhhI/UvA81CGpKyB/DipuzXdps3w000UhJ4eIbqOYLm4/90y4Ck4+dcheKBUp+Xp1pyGNCHG0PZnGzw4KQ+anYsBJytKeJOXegg+TnGVNB1duI6QCuiMHDY48hZyaBN8p5IFare+LXejSToCENkNz1t4sz7+4FJjYyfq4QgGPXZOpm8+oAD825fG3hYoWDWwpw6s185Bhfanyl4PcU6TDKTocFtREI+nQDHaU1qgcCYQF1xf6MKx2MPE4UJpqJ74VIE2n278ePKCrg6SHdFxRUIbal7TN5qMNCVCYngtlmeSYnIB+2kpRVylEFubzOsoR2uE4WZbIsUIxirHjv8kov6MFuFPPv5ZqpUnTvCsksJtZ6RbSaBlCXcfUYbIzQfTOAcrTvr96ZMO3SDottNJA5kPcj2S1T9F+e/zXu5d4="
  matrix:
    - VERSION=latest

before_script:
  - cd src/
  - IMAGE_NAME="chesszebra/$(echo "$TRAVIS_REPO_SLUG" | cut -c 25-):${VERSION}"

script:
  - docker build -t "$IMAGE_NAME" .

after_success:
  - docker login --username $DOCKER_USER --password $DOCKER_PASS
  - docker push $IMAGE_NAME

after_script:
  - docker images

notifications:
  email: false
