language: bash

services: docker

env:
  global:
    - secure: "GqxiCVwSUY138INNYSU+Z4l3pHMeO7bBtQek1cvKptVOijlP5XK066So40OYLdwZrPdisHWiBvx/VoeIG5Uv+7s+8L8uvbAnVDOP3Pf6ykDqp/tu+s10yBJlCFjbMtcMCtp2CSeZRBJ/7AKnK5C8RsrpJbvcTRmBIgrkzxXGcgvfTWyXUWj4n9mMfq0zJp3MX8lfupwd/9U2IioMptKTddiQ3lrqRLAQUyresJwdRon6NpWbEUFbe8h+NwRv6nSlEu51D9KIXvfSVpkTx6JhEIydz2Zj+q+e6t9xvIJjjdNT2A2NvrC8Gwe2yx2JG56+Bxz8Ew32yjJjtztxyaMOq2Bg+9URArrVeCiS/zT2JnSHImu5z3cD8P5uIZS8g2wA5yaIZtYPovjrZUD50SsrLVn2HlYkB3KoS5amFcO0z8f1RiATLGpcbU9HxS/JecW2FXHlV8NOzrZg9LhDEI5ZcQKgTElHe07OZvBx+9xw+jqrohXngUBTcUilJsCwkbd+lHXJo/LGlRPeRVjRle6n2u49Gavnr5cDF49OK+4JKbgFnaU/Ft2n86Zkm8BgRSEfpqZUXBADhqZvHqcbx2OugtsWiWx2VVB6m3ZNR5Cz1iDr+gT+FILoMwN027mavsZ4OdtgVQLtwl3OydlEbgwRcPsQFh9MyP+wft0pSwubVW0="
    - secure: "UKFnHghBSakYthQMnmysrAWg3bW4kWdMkZoU/AIWhmE8Umr+7xnBnAVbAbU558v6pRc7iLPVpxQA89My8HON5qt6BXwrmhIc29DW+qe0KBP97xgy/uP/OVxEQy2giFvi0w/wrG/IEqPGawA9kb1eAmhyli+HxDOgIC4cwmLuetDi0qRMpm5ZOtgm+FC38OFpV4QcioWTNBYfa2yWYIJz5tXjcTWIRsjQbhdWRfGPP8c3DNCGoO3mCTobMAS/F4SmnvZ9DZr1be5OrFgWaL7SbZX+BkMXhO08qt3p8cs7Xg95FkG94H/8yfu32s//sXj8IQtNghrHCCfSb4NnbzjPEYAP/zL20DYVfA7Gw6ujnfQXgIg2qGCK+8HUQbjawwdlhkRHzKU3nNk9e6A4ptlM8qxMPiTuu3no3Tf4GDNhJ1uniobxUxGuu6+4Jsyt6c2daeyEuAjbJ+W7xl0HM+2ERIffRsT8W0poonA+HX+vDyeNdJfhJ0IfZdvna30mEsqBIf2HGxqOgapQDZW985H+iF+MaYPAIvEStDq/9Rf9EzyHsGHHekp4SW8JYtKMuJfYanRXrReWabaPnUEmsqGCfi+ECwaCeD2AxTXtUN7IqP61FqMymVOeBew4vG7kGGomMN2ZW9No1ItGzU6Qcmr9SS3YuDIxj8v4wHMjLeSysZs="
  matrix:
    - VERSION=latest

before_script:
  - cd src/
  - IMAGE_NAME="chesszebra/$(echo "$TRAVIS_REPO_SLUG" | cut -c 25-):${VERSION}"

script:
  - docker build -t "$IMAGE_NAME" .
  - docker tag "$IMAGE_NAME" "$IMAGE_NAME"

after_success:
  - docker login --username $DOCKER_USER --password $DOCKER_PASS
  - docker push $IMAGE_NAME

after_script:
  - docker images

notifications:
  email: false
